// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class zerodha : Exchange
{
    public zerodha (object args = null): base(args) {}

    public async Task<object> publicGetInstruments (object parameters = null)
    {
        return await this.callAsync ("publicGetInstruments",parameters);
    }

    public async Task<object> publicGetInstrumentsExchange (object parameters = null)
    {
        return await this.callAsync ("publicGetInstrumentsExchange",parameters);
    }

    public async Task<object> publicGetQuote (object parameters = null)
    {
        return await this.callAsync ("publicGetQuote",parameters);
    }

    public async Task<object> publicGetQuoteLtp (object parameters = null)
    {
        return await this.callAsync ("publicGetQuoteLtp",parameters);
    }

    public async Task<object> publicGetQuoteOhlc (object parameters = null)
    {
        return await this.callAsync ("publicGetQuoteOhlc",parameters);
    }

    public async Task<object> privateGetUserProfile (object parameters = null)
    {
        return await this.callAsync ("privateGetUserProfile",parameters);
    }

    public async Task<object> privateGetUserMargins (object parameters = null)
    {
        return await this.callAsync ("privateGetUserMargins",parameters);
    }

    public async Task<object> privateGetUserMarginsSegment (object parameters = null)
    {
        return await this.callAsync ("privateGetUserMarginsSegment",parameters);
    }

    public async Task<object> privateGetPortfolioPositions (object parameters = null)
    {
        return await this.callAsync ("privateGetPortfolioPositions",parameters);
    }

    public async Task<object> privateGetPortfolioHoldings (object parameters = null)
    {
        return await this.callAsync ("privateGetPortfolioHoldings",parameters);
    }

    public async Task<object> privateGetOrders (object parameters = null)
    {
        return await this.callAsync ("privateGetOrders",parameters);
    }

    public async Task<object> privateGetOrdersOrderId (object parameters = null)
    {
        return await this.callAsync ("privateGetOrdersOrderId",parameters);
    }

    public async Task<object> privateGetTrades (object parameters = null)
    {
        return await this.callAsync ("privateGetTrades",parameters);
    }

    public async Task<object> privateGetTradesOrderId (object parameters = null)
    {
        return await this.callAsync ("privateGetTradesOrderId",parameters);
    }

    public async Task<object> privateGetInstrumentsHistoricalInstrumentTokenInterval (object parameters = null)
    {
        return await this.callAsync ("privateGetInstrumentsHistoricalInstrumentTokenInterval",parameters);
    }

    public async Task<object> privatePostOrdersVariety (object parameters = null)
    {
        return await this.callAsync ("privatePostOrdersVariety",parameters);
    }

    public async Task<object> privatePostOrdersVarietyOrderId (object parameters = null)
    {
        return await this.callAsync ("privatePostOrdersVarietyOrderId",parameters);
    }

    public async Task<object> privatePostPortfolioPositions (object parameters = null)
    {
        return await this.callAsync ("privatePostPortfolioPositions",parameters);
    }

    public async Task<object> privatePutOrdersVarietyOrderId (object parameters = null)
    {
        return await this.callAsync ("privatePutOrdersVarietyOrderId",parameters);
    }

    public async Task<object> privateDeleteOrdersVarietyOrderId (object parameters = null)
    {
        return await this.callAsync ("privateDeleteOrdersVarietyOrderId",parameters);
    }

}