<?php

namespace ccxt\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class zerodha extends \ccxt\Exchange {
    public function public_get_instruments($params = array()) {
        return $this->request('instruments', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_instruments_exchange($params = array()) {
        return $this->request('instruments/{exchange}', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_quote($params = array()) {
        return $this->request('quote', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_quote_ltp($params = array()) {
        return $this->request('quote/ltp', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_quote_ohlc($params = array()) {
        return $this->request('quote/ohlc', 'public', 'GET', $params, null, null, array());
    }
    public function private_get_user_profile($params = array()) {
        return $this->request('user/profile', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_user_margins($params = array()) {
        return $this->request('user/margins', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_user_margins_segment($params = array()) {
        return $this->request('user/margins/{segment}', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_portfolio_positions($params = array()) {
        return $this->request('portfolio/positions', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_portfolio_holdings($params = array()) {
        return $this->request('portfolio/holdings', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_orders($params = array()) {
        return $this->request('orders', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_orders_order_id($params = array()) {
        return $this->request('orders/{order_id}', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_trades($params = array()) {
        return $this->request('trades', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_trades_order_id($params = array()) {
        return $this->request('trades/{order_id}', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_instruments_historical_instrument_token_interval($params = array()) {
        return $this->request('instruments/historical/{instrument_token}/{interval}', 'private', 'GET', $params, null, null, array());
    }
    public function private_post_orders_variety($params = array()) {
        return $this->request('orders/{variety}', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_orders_variety_order_id($params = array()) {
        return $this->request('orders/{variety}/{order_id}', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_portfolio_positions($params = array()) {
        return $this->request('portfolio/positions', 'private', 'POST', $params, null, null, array());
    }
    public function private_put_orders_variety_order_id($params = array()) {
        return $this->request('orders/{variety}/{order_id}', 'private', 'PUT', $params, null, null, array());
    }
    public function private_delete_orders_variety_order_id($params = array()) {
        return $this->request('orders/{variety}/{order_id}', 'private', 'DELETE', $params, null, null, array());
    }
    public function publicGetInstruments($params = array()) {
        return $this->request('instruments', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetInstrumentsExchange($params = array()) {
        return $this->request('instruments/{exchange}', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetQuote($params = array()) {
        return $this->request('quote', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetQuoteLtp($params = array()) {
        return $this->request('quote/ltp', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetQuoteOhlc($params = array()) {
        return $this->request('quote/ohlc', 'public', 'GET', $params, null, null, array());
    }
    public function privateGetUserProfile($params = array()) {
        return $this->request('user/profile', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetUserMargins($params = array()) {
        return $this->request('user/margins', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetUserMarginsSegment($params = array()) {
        return $this->request('user/margins/{segment}', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetPortfolioPositions($params = array()) {
        return $this->request('portfolio/positions', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetPortfolioHoldings($params = array()) {
        return $this->request('portfolio/holdings', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetOrders($params = array()) {
        return $this->request('orders', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetOrdersOrderId($params = array()) {
        return $this->request('orders/{order_id}', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetTrades($params = array()) {
        return $this->request('trades', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetTradesOrderId($params = array()) {
        return $this->request('trades/{order_id}', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetInstrumentsHistoricalInstrumentTokenInterval($params = array()) {
        return $this->request('instruments/historical/{instrument_token}/{interval}', 'private', 'GET', $params, null, null, array());
    }
    public function privatePostOrdersVariety($params = array()) {
        return $this->request('orders/{variety}', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostOrdersVarietyOrderId($params = array()) {
        return $this->request('orders/{variety}/{order_id}', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostPortfolioPositions($params = array()) {
        return $this->request('portfolio/positions', 'private', 'POST', $params, null, null, array());
    }
    public function privatePutOrdersVarietyOrderId($params = array()) {
        return $this->request('orders/{variety}/{order_id}', 'private', 'PUT', $params, null, null, array());
    }
    public function privateDeleteOrdersVarietyOrderId($params = array()) {
        return $this->request('orders/{variety}/{order_id}', 'private', 'DELETE', $params, null, null, array());
    }
}
